FROM af0x/hlds:rehlds
#RUN apt-get -y install mc
## back weapons https://forums.alliedmods.net/showthread.php?p=359356
COPY ./cstrike ./cstrike
RUN echo "backweapons.amxx" >> ./cstrike/addons/amxmodx/configs/plugins.ini && \
echo "mapchooser.amxx" >> ./cstrike/addons/amxmodx/configs/plugins.ini && \
echo "linux addons/resemiclip/resemiclip_mm_i386.so" >> ./cstrike/addons/metamod/plugins.ini




#ENTRYPOINT ./hlds_run -game cstrike + map de_dust2