version: "3.8"

services:
  cs:
    profiles:
      - all
      - cs
    image: af0x/rehlds:cs
    volumes:
      - ./docker/cs/mapcycle.txt:/hlds/cstrike/mapcycle.txt
      - ./docker/cs/server.cfg:/hlds/cstrike/server.cfg
      - ./docker/cs/maps:/hlds/cstrike/maps
      - ./docker/users.ini:/hlds/cstrike/addons/amxmodx/configs/users.ini
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
    environment:
      RCON_PASSWORD: asjop2340239857uG
      MAP: de_dust2_2x2
      PORT: 27015
  csdm:
    profiles:
      - all
      - csdm
    image: af0x/rehlds:csdm
    volumes:
      - ./docker/cs/mapcycle.txt:/hlds/cstrike/mapcycle.txt
      - ./docker/cs/server.cfg:/hlds/cstrike/server.cfg
      - ./docker/cs/maps:/hlds/cstrike/maps
      - ./docker/users.ini:/hlds/cstrike/addons/amxmodx/configs/users.ini
    ports:
      - "27017:27017/tcp"
      - "27017:27017/udp"
    environment:
      RCON_PASSWORD: asjop2340239857uG
      MAP: de_dust2_2x2
      PORT: 27017
  half-life:
    profiles:
      - all
      - hl
    image: af0x/rehlds:hl
    volumes:
      - ./docker/half-life/mapcycle.txt:/hlds/valve/mapcycle.txt
      - ./docker/half-life/server.cfg:/hlds/valve/server.cfg
      - ./docker/half-life/maps:/hlds/valve/maps
      - ./docker/users.ini:/hlds/valve/addons/amxmodx/configs/users.ini
    ports:
      - "27016:27016/tcp"
      - "27016:27016/udp"
    environment:
      RCON_PASSWORD: asjop2340239857uG
      MAP: 1337_Street
      PORT: 27016

networks:
  default:
    external: true
    name: games-net
