FROM af0x/hlds:base
COPY ./hlds .
RUN echo "backweapons.amxx" >> ./cstrike/addons/amxmodx/configs/plugins.ini && \
echo "mapchooser.amxx" >> ./cstrike/addons/amxmodx/configs/plugins.ini && \
echo "linux addons/resemiclip/resemiclip_mm_i386.so" >> ./cstrike/addons/metamod/plugins.ini
